let matches = [{
    "name":"Jose",
    "photo":"public/assets/person-1.jpg",
    "scores":[
        5,
        1,
        4,
        4,
        5,
        1,
        2,
        5,
        4,
        1
      ]
  },
  {
    "name":"Jennifer",
    "photo":"https://media.licdn.com/mpr/mpr/shrinknp_400_400/p/6/005/064/1bd/3435aa3.jpg",
    "scores":[
        1,
        2,
        4,
        3,
        2,
        5,
        2,
        5,
        2,
        4
      ]
  }
]
module.exports = matches